### ISSUE TITLE
document difference between nio and bufio

### ISSUE THREAD

**Issue by 6543** [djherbis/nio#6]

**Comment by djherbis** [comment]
Assuming you want me to compare:
https://pkg.go.dev/github.com/djherbis/nio
vs. 
https://pkg.go.dev/bufio

nio is just a Buffered version of io.Pipe, the buffer is an Interface so you can plug in any buffer you wish. Pre-built buffers are in 
https://pkg.go.dev/github.com/djherbis/buffer.
Nio also includes an io.Copy replacement that just uses io.Pipe under the hood to do the copy in parallel (reads into the buffer and then into the Writer).

bufio is the standard librarys buffered io primitives. 

Does that help?

**Comment by 6543** [comment]
yes thanks :)

**Comment by 6543** [comment]
context: `https://github.com/go-gitea/gitea/pull/19448` vs `https://github.com/go-gitea/gitea/pull/19454` ...
