### ISSUE TITLE
add support for ReadSeekCloser

### ISSUE THREAD

**Issue by 6543** [djherbis/nio#7]
add an Seek interface

**Comment by djherbis** [comment]
@6543 If the type you want already has ReadAt then just use [io.NewSectionReader](https://pkg.go.dev/io#NewSectionReader) which can do Seek on a ReadAt type.

**Comment by 6543** [comment]
well it would be a way to make nio a nice "just wrap and use" lib ... but I already solved it for my usecase in an other way ...
... so dont hurry, but let it be a nice idea

if it does not make sense from an internal ponint of view to add ... just close this issue

**Comment by djherbis** [comment]
I wouldn't really be doing anything that NewSectionReader can't do:

buf := ... some buffer with ReadAt...
r := io.NewSectionReader(buf, 0, buf.Len())

And now you have a Seeking Reader.

It doesn't seem like there's a reason to add Seek in this case.

**Comment by 6543** [comment]
ok, thanks for looking into this anyway :)
